# Using free-form deformation model
model:
  name: FFD
  stride: [8, 8, 5]
# Loss terms of objective function to minimize
energy:
  seg: [1, MSE]
  be: [0.005, BSplineBending]
# Optimization scheme and parameters
optim:
  name: Adam
  step_size: 0.001
  min_delta: -0.01
  max_steps: 100
# Gaussian resolution pyramid
pyramid:
  dims: ["x", "y"]
  levels: 3
  spacing: [1.25, 1.25, 2.0]
