version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    # https://github.com/readthedocs/readthedocs.org/issues/8890#issuecomment-1098436579
    post_create_environment:
      - python -m pip install --no-cache-dir --no-deps .
    pre_build:
      - jupyter-book config sphinx docs/

conda:
  environment: conda/environment.linux-64.yml

sphinx:
  builder: html
  fail_on_warning: false