# Create conda environment with all prerequisites of this project installed
# using command: conda env create --name deepali --file conda.yaml
channels:
  - pytorch
  - nvidia
  - simpleitk
  - conda-forge
  - defaults
dependencies:
  - black=22.3
  - boto3=1.18
  - cudatoolkit=11.1
  - dacite=1.6
  - flake8=3.9
  - ipykernel
  - ignite=0.4
  - jupyter
  - notebook
  - numpy=1.21
  - pandas=1.3
  - pip=21.2
  - pytest=6.2
  - python>=3.7
  - pytorch=1.9
  - pyyaml=5.4
  - scipy=1.7
  - tensorboard=2.6
  - typing-extensions=3.10
  - vtk=9.0
  - SimpleITK=2.0
  - pip:
    - torchinfo==1.5
