# Create conda environment with all prerequisites of this project installed
# using command: conda env create --name deepali --file conda.yaml
channels:
  - pytorch
  - simpleitk
  - conda-forge
  - defaults
dependencies:
  - black=20.8b1
  - boto3=1.17
  - cudatoolkit=11.1
  - dacite=1.6
  - flake8=3.9
  - ignite=0.4
  - numpy=1.20
  - pytest=6.2
  - python=3.8
  - pytorch=1.8.1
  - pyyaml=5.4
  - scipy=1.6
  - tensorboard=2.4
  - typing-extensions=3.7
  - vtk=9.0
  - SimpleITK=2.0
  - pip:
    - torchinfo==0.1
