name: checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check:
    name: Check with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - 'pyproject.toml'
              - 'src/**'
              - 'tests/**'
      - uses: actions/checkout@v4
        if: steps.filter.outputs.changed == 'true'
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.py }}
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install package
        if: steps.filter.outputs.changed == 'true'
        run: |
          pip install --upgrade pip
          python -m pip install .[all]
      - name: Run test suite
        if: steps.filter.outputs.changed == 'true'
        run: pytest tests