name: GitHub Pages

on:
  push:
    branches:
      - main
      - docs
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: $CONDA/bin/conda update --name base --file conda/environment.linux-64.lock
    - name: Build Pages
      run: |
        $CONDA/bin/conda run --name base pip install .
        $CONDA/bin/conda run --name base jupyter-book build docs
    - name: Set up Pages
      uses: actions/configure-pages@v3
    - name: Upload Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_build/html
    - id: deployment
      name: Deploy Pages
      uses: actions/deploy-pages@v2